### ISSUE TITLE
Add User Details to pagerduty_incident_info

### ISSUE THREAD

**Issue by muralikanagala** [webdevops/pagerduty-exporter#2]
The exporter is great! Can you also add the detail of the user to which the incident is assigned in the metric "pagerduty_incident_info"?

**Comment by mblaschke** [comment]
Isn't it already available via metric `pagerduty_incident_status{type="assignment"}`? I'm getting an array so there can be more then one person.

**Comment by muralikanagala** [comment]
Thanks for checking!
I will run it once again and let you know.

**Comment by muralikanagala** [comment]
Hi Markus - You are right. I see the user detail in the incident status metric. I will use Promql to convert it to user name from another metric.  Thanks a lot!
