### ISSUE TITLE
IncedentID not exported

### ISSUE THREAD

**Issue by shiroyasha** [webdevops/pagerduty-exporter#8]
First of all, thanks for working on this scraper!

I've noticed that the `incidentID` is not exporter to Prometheus, for `pagerduty_incident_status` and `pagerduty_incident_info metrics`.

It is exported here https://github.com/webdevops/pagerduty-exporter/blob/master/metrics_incident.go#L44, but interestingly enough only the `time`, `type`, `userID` and `value` are accessible in Prometheus.

Do you have maybe a tip where to look? Is this a bug?

**Comment by mblaschke** [comment]
Thanks, fixed with version `0.13.0`.

Strange, PagerDuty SDK publishes an empty `ID` and the correct `Id`. In other places they're using `ID`.. really confusing :(

**Comment by mblaschke** [comment]
There is a bug in the pagerduty-SDK

**Comment by shiroyasha** [comment]
Thank you for the fix.

**Comment by mblaschke** [comment]
Please try 0.13.1
