### ISSUE TITLE
[Documentation] Add information how to run dockerized version

### ISSUE THREAD

**Issue by RiRa12621** [webdevops/pagerduty-exporter#9]
While running the binary is more or less self-explanatory, I feel like that knowledge should not be assumed, as well as information about how to run the dockerized version.
Especially with that information missing, there's also no information on how to run it on dockerhub.

I would like to propose an addition to the readme that simply explains how to get the binary and how to run the dockerized version so people have an easy entry to using this exporter.

**Comment by techcubs** [comment]
I would like to run it in docker as well but I am struggling with this.

I added the following to **docker-compose.yml**
pagerduty-exporter:
    image: webdevops/pagerduty-exporter
    hostname: localhost
    container_name: pagerduty-exporter
    command:
      - '--pagerduty.authtoken==RandonTokenGeneratedViaUserProfile'
    restart: unless-stopped
    ports:
      -"9138:9138"
   
Do we need to expose any ports? how will prometheus scrape this ?

For **prometheus.yml** I added:
  - job_name: 'pagerduty-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['pagerduty-exporter:9138']

But its still showing as down in Prometheus with "connection refused" status message.

**Comment by RiRa12621** [comment]
no feedback from maintainers since 3 month, closing this going to fork

**Comment by mblaschke** [comment]
@RiRa12621 this tool is still maintained, please feel free to submit a PR
due to corona i didn't hat so much time, hope that it's getting better in the next weeks.

PS: Ping me on twitter if I don't see an issue.

**Comment by RiRa12621** [comment]
Ok cool, I'll try to find some time to add some additions to the readme
